route:
      group_by: ['alertname', 'job']

      group_wait: 10s
      group_interval: 1m
      repeat_interval: 10m

      receiver: discord

    receivers:
    - name: discord
      discord_configs:
      - webhook_url: TODO CHANGE ME
