    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - iot-project-alerts.yml

    alerting:
      alertmanagers:
      - static_configs:
        - targets: ['alertmanager:9093']

    scrape_configs:
      - job_name: iot_project
        scrape_interval: 1s
        scrape_timeout: 1s
        scheme: http
        static_configs:
        - targets: ['10.42.0.2']
